Remove comment above shebang in bin/console template
rubygems/rubygems pull request #3927
Opened 2020-09-03 03:35 UTC by speckins

In an executable script, the shebang line should be the first line (the
file needs to start with the bytes 0x23 0x21).  Putting a comment above
it will break the script.

2020-09-03 09:38 UTC, deivid-rodriguez requested changes
Thank you, nice catch!

As illustrated by the failing specs, you need to restore the `# frozen_string_literal: true` line as the second line in the file.

2020-09-03 12:15 UTC, speckins commented
I've made the requested changes.

2020-09-03 12:22 UTC, deivid-rodriguez commented
Thanks! Just one final request, could you add a couple of lines below this code here:

https://github.com/rubygems/rubygems/blob/2ceb821579d491219ce352b858120f7b5c0a467b/bundler/spec/commands/newgem_spec.rb#L377-L378

to assert that the first two characters in the generated binstub are "!#"?

That way we add some test coverage for this bug fix.

2020-09-03 13:36 UTC, speckins commented
I appended those expectations to that same test rather than creating a separate test; I hope that's okay.

2020-09-03 13:40 UTC, deivid-rodriguez approved these changes
Yes, it looks really good, thanks!

2020-09-04 02:35 UTC, hsbt commented
👍

2020-09-04 02:35 UTC, merged