Don't let bundler retry on non-network error
rubygems/rubygems pull request #5270
Opened 2022-01-10 02:02 UTC by ximenasandoval

## What was the end-user or developer problem that led to this PR?

As described in #5161, `bundle` will retry on any error, even if it isn't a network error.

## What is your fix for the problem, implemented in this PR?
By passing the `StandardError` class to the `Retry` object, we are making sure that `bundle` won't retry if a StandardError occurs.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

2022-01-17 10:12 UTC, deivid-rodriguez requested changes
Hei @ximenasandoval, using `Bundler::Fetcher::HTTP_ERRORS` feels great to me. But this logic should live inside `Bundler::Retry` in my opinion, so that we can short-circuit from inside the class, and thus in general, not just in this particular situation.

The way I would approach this is to change `Bundler::Retry` to receive an optional list of retryable exceptions as the second parameter to `initialize`, instead of receiving a non-retryable list of exceptions, and then pass `HTTP_ERRORS` to it. What do you think?

2022-01-17 17:24 UTC, ximenasandoval commented
Hi! It sounds great! I was also thinking this fix was a little awkward 😅  I'll be working on that fix. I wasn't sure about changing the `Retry` class, but this way will be clearer for future situations.

2022-01-21 16:29 UTC, ximenasandoval commented
Hi! Sorry for the inactivity, I just wanted to share that I'm still working on this issue 🙌🏽  but due to some activities/issues I haven't been able to work as much as I wanted. I'll do my best to finish it as soon as possible 😄 .

While looking at other files where `Retry` is used I notice that other classes use this list of non-retryable exceptions 😮  so changing this parameter would affect these classes. I think I could add another parameter for these retryable exceptions and implement that logic if that list isn't `nil`

2022-01-22 04:32 UTC, deivid-rodriguez commented
Hi @ximenasandoval, don't worry about the inactivity :)

> While looking at other files where Retry is used I notice that other classes use this list of non-retryable exceptions 😮 so changing this parameter would affect these classes. I think I could add another parameter for these retryable exceptions and implement that logic if that list isn't nil

Yes, my idea was to change the `initialize` signature and adapt current usages. As far as I can see, the existing parameter is only used twice to receive a list of errors that need to be treated as non retryable failures (in `bundler/lib/bundler/fetcher.rb` and `bundler/lib/bundler/fetcher/dependency.rb`, where that `FAIL_ERRORS` list is passed). In my opinion, the same change we're making here makes sense there too. Any other non network errors should not be retried, so it doesn't make sense to me to pass a `FAIL_ERRORS` denylist, but an allowlist is better instead.

I don't think there's any problem in tweaking `Retry.new` signature since this class is only meant for internal usage as far as I know.

2022-01-31 19:00 UTC, deivid-rodriguez reviewed
Thanks @ximenasandoval. I left a review. I think this is not currently doing what we want, since I misunderstood the classes included in `HTTP_ERRORS`.

2022-02-04 03:26 UTC, ximenasandoval commented on bundler/lib/bundler/retry.rb
> +      @exceptions = Array(exceptions) || [] # Allow list of exceptions
Hi! We could change it to `@retryable_exceptions` since now the class gets a list of the allowed exceptions to be retried o:

2022-02-04 03:27 UTC, ximenasandoval commented on bundler/lib/bundler/retry.rb
> +      !@exceptions.empty? && @exceptions.none? {|k| e.is_a?(k) }
I'm going to check on that! 😄

2022-02-04 03:30 UTC, ximenasandoval commented on bundler/lib/bundler/fetcher.rb
> +      Bundler::Retry.new("fetcher", HTTP_ERRORS).attempts do
Oh okay 😲 I'll first try to get manually the exceptions that are in `FAIL_ERRORS` but not in `HTTP_ERRORS`

2022-02-04 10:43 UTC, deivid-rodriguez commented on bundler/lib/bundler/retry.rb
> +      @exceptions = Array(exceptions) || [] # Allow list of exceptions
Yeah, sorry, that's what I meant 👍.

2025-07-02 14:19 UTC, deivid-rodriguez commented
Closing since I believe these days this problem is mostly fixed!

2025-07-02 14:19 UTC, closed without merging